/* eslint-disable */
const DATA = {
  section1: {
    id: 'section1',
    label: 'Section 1 — Hero',
    headline: 'Private data infrastructure for tokenized finance',
    subheadings: [
      'The platform institutions use to govern access, format and intended purpose across all digital asset operations.',
      'Noves gives institutions a single system to control who sees their private chain data, in what form, and for what purpose.',
      'The platform institutions use to govern access, format, and purpose across all digital asset operations.',
    ],
  },

  section2: {
    id: 'section2',
    label: 'Section 2 — This Is For You',
    headlines: [
      'Visibility without exposure',
      'Visibility without the exposure',
      '100% visibility, 0% exposure',
      'See everything. Expose nothing.',
      'Full visibility, Zero exposure.',
      'Embedded data privacy on any chain',
      'Data disclosure on your terms',
      'Share confidently. Control completely.',
      'Authorised eyes only.',
      'Ringfence your data. Control the gate.',
      'Exercise control over your data',
      'Control access to your data',
    ],
    subheadings: [
      'Full control into who has access to your data, and on what terms.',
      'The right data reaches the right people and only them.',
      'Full visibility into your blockchain data. Total control over who sees it.',
      'The data sentinel you have always needed.',
      'Standing watch over every data request',
      'The sentinel between your data and authorised people',
      'A trusted data environment for every chain interaction',
      'The Noves sentinel provides data privacy and control functionality for all chains.',
    ],
    privateDataOptions: [
      { id: 'canton-validator-ops', label: 'Canton validator ops' },
      { id: 'intraday-settlement',  label: 'Intraday settlement' },
      { id: 'on-prem-ledgers',      label: 'On-prem ledgers' },
      { id: 'otc-transfers',        label: 'OTC transfers' },
      { id: 'private-transfers',    label: 'Private transfers' },
    ],
    publicDataOptions: [
      { id: 'rwa-holdings',       label: 'RWA holdings' },
      { id: 'ethereum-positions', label: 'Ethereum positions' },
      { id: 'token-transfers',    label: 'Token transfers' },
      { id: 'staking-rewards',    label: 'Staking rewards' },
      { id: 'dex-activity',       label: 'DEX activity' },
    ],
    outputCategoryPresets: {
      0: [ // Finance
        { label: 'Finance', desc: 'Reporting, reconciliation and position data' },
      ],
      1: [ // Regulator
        { label: 'Tax planners & auditors', desc: '' },
        { label: 'Regulator', desc: 'Audit trail and regulatory outputs on demand' },
      ],
    },

    sentinelOptions: [
      { id: 0, label: 'The sentinel' },
      { id: 1, label: 'Controlled access layer' },
      { id: 2, label: 'The governance layer' },
      { id: 3, label: 'Governed access' },
    ],
  },

  section3: {
    id: 'section3',
    label: 'Section 3 — In What Way',
    headlines: [
      'Remove operational burden, stay in control.',
      'Remove operational burden without removing control',
      'Proactive, always-on compliance and reporting.',
      'From raw data to reportable output.',
      'Automate your blockchain operations',
      'From manual workarounds to always-on data operations',
      'Make your data work for you',
      'Navigate your private chain data with ease',
    ],
    subheadings: [
      'Noves Data Platform simplifies operations, reporting and compliance, with guardrails to ensure privacy and security across your deployment.',
      'An access and control layer that respects enterprise trust boundaries: governed and permission-aware throughout.',
      'Meet supervisory expectations for traceability and control without adding new friction or bureaucracy.',
    ],
    stages: [
      { id: 'access',    label: 'Access',    description: 'Real-time visibility into positions, flows, and network activity across your blockchain data.' },
      { id: 'translate', label: 'Translate', description: 'Raw transaction data is standardized and structured, mapped to institutional reporting frameworks.' },
      { id: 'reconcile', label: 'Reconcile', description: 'Audit-ready outputs with automated reconciliation across your on-chain activity.' },
      { id: 'report',    label: 'Report',    description: 'Proactive compliance, traceability and operational reporting.' },
    ],
    darkStripItems: ['SOC 2 Type 2', 'Chain agnostic', 'Multi-validator support'],
  },

  section4: {
    id: 'section4',
    label: 'Section 4 — Growth Story',
    headlines: [
      'Build trust not workarounds',
      'Stop building workarounds. Focus on your business logic',
      'The data layer that scales with you.',
      'Compliance, audit and reporting that doesn\'t slow you down',
      'Noves does the busy work for you',
      'Companies that build trust grow faster',
      'Always-on data infrastructure',
      'Stop data governance being your bottleneck',
      'The institutions that get their data layer right move faster',
      'Make operational speed your competitive advantage',
    ],
    subheadings: [
      'Always-on infrastructure that removes bottlenecks and helps you move faster.',
      'Reporting, audits and compliance that coexist with your business operations.',
      'Institutions with always-on data infrastructure can move faster and scale their operations without adding headcount.',
      'Say goodbye to manual data processes.',
      'Always-on infrastructure that scales with your operations',
      'The institutions that get their data layer right move faster',
    ],
    blocks: [
      { id: 14, label: 'Close at finance speed',              copy: 'Reconciliation, period-end reporting, and audit responses for digital asset activity run on the same calendar as the rest of your finance function. No multi-week reconciliation marathons. No quarter-end heroics.' },
      { id: 15, label: 'Same team, more output',              copy: 'As your digital asset book grows in volume, complexity, and counterparty count, the team running it doesn\'t need to grow with it. The platform absorbs the operational load that would otherwise become headcount.' },
      { id: 16, label: 'Expand without rebuilding',           copy: 'Add a new chain, asset class, counterparty, or transaction type as a configuration task, not an engineering one. What used to take quarters, happens in days.' },
      { id: 0,  label: 'Maximize operational efficiency',      copy: 'Noves data layer scales with you for every new validator you add, every new counterparty you onboard, every new transaction type.' },
      { id: 1,  label: 'No new risk surface',                  copy: 'Your data is kept private by default with the ability to share securely with third parties when required. No data exfiltration, no risk exposure.' },
      { id: 2,  label: 'Automatic data ops scaling',           copy: 'Expand your footprint knowing the data infrastructure will scale with you. Every new validator, every new counterparty, every new transaction type can scale automatically.' },
      { id: 3,  label: 'Onboard counterparties faster',        copy: 'Counterparty onboarding that used to take weeks, resolved in days.' },
      { id: 4,  label: 'Always-on compliance function',        copy: 'When your compliance function runs continuously, regulatory requests can be answered on demand.' },
      { id: 5,  label: 'Scale operations without adding headcount', copy: 'Every new validator, counterparty and transaction type handled automatically.' },
      { id: 6,  label: 'Data accuracy & completeness',         copy: 'Noves classifies every transaction type, populates every field, and leaves nothing for your team to correct manually.' },
      { id: 7,  label: 'Days to deploy',                       copy: 'Up and running via Docker Compose or Kubernetes. Your team stays in control throughout.' },
      { id: 8,  label: 'No engineering dependency',            copy: 'Your finance team shouldn\'t need the engineering team to pull data. Always-on access to positions, flows and reconciliation outputs.' },
      { id: 9,  label: 'Build trust faster',                   copy: 'Institutions that can demonstrate data governance in real time build trust faster with counterparties and regulators.' },
      { id: 10, label: 'Audit trails on demand',               copy: 'Audit preparation that used to be a nine-month project, now always-on.' },
      { id: 11, label: 'Instant regulatory requests',          copy: 'Regulatory requests answered on demand, not assembled after the fact.' },
      { id: 12, label: 'Validator cost management',            copy: 'Know your Canton balance, prevent operational stops before they happen.' },
      { id: 13, label: 'Traffic attribution',                  copy: 'Know which operations are driving cost, bill counterparties accurately, scale the right things.' },
    ],
  },
};
